/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: lstore.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class AddrBookRecord extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        threadID?: Uint8Array;
        peerID?: Uint8Array;
        addrs?: AddrBookRecord.AddrEntry[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("threadID" in data && data.threadID != undefined) {
                this.threadID = data.threadID;
            }
            if ("peerID" in data && data.peerID != undefined) {
                this.peerID = data.peerID;
            }
            if ("addrs" in data && data.addrs != undefined) {
                this.addrs = data.addrs;
            }
        }
    }
    get threadID() {
        return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array()) as Uint8Array;
    }
    set threadID(value: Uint8Array) {
        pb_1.Message.setField(this, 1, value);
    }
    get peerID() {
        return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array()) as Uint8Array;
    }
    set peerID(value: Uint8Array) {
        pb_1.Message.setField(this, 2, value);
    }
    get addrs() {
        return pb_1.Message.getRepeatedWrapperField(this, AddrBookRecord.AddrEntry, 3) as AddrBookRecord.AddrEntry[];
    }
    set addrs(value: AddrBookRecord.AddrEntry[]) {
        pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    static fromObject(data: {
        threadID?: Uint8Array;
        peerID?: Uint8Array;
        addrs?: ReturnType<typeof AddrBookRecord.AddrEntry.prototype.toObject>[];
    }): AddrBookRecord {
        const message = new AddrBookRecord({});
        if (data.threadID != null) {
            message.threadID = data.threadID;
        }
        if (data.peerID != null) {
            message.peerID = data.peerID;
        }
        if (data.addrs != null) {
            message.addrs = data.addrs.map(item => AddrBookRecord.AddrEntry.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            threadID?: Uint8Array;
            peerID?: Uint8Array;
            addrs?: ReturnType<typeof AddrBookRecord.AddrEntry.prototype.toObject>[];
        } = {};
        if (this.threadID != null) {
            data.threadID = this.threadID;
        }
        if (this.peerID != null) {
            data.peerID = this.peerID;
        }
        if (this.addrs != null) {
            data.addrs = this.addrs.map((item: AddrBookRecord.AddrEntry) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.threadID.length)
            writer.writeBytes(1, this.threadID);
        if (this.peerID.length)
            writer.writeBytes(2, this.peerID);
        if (this.addrs.length)
            writer.writeRepeatedMessage(3, this.addrs, (item: AddrBookRecord.AddrEntry) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddrBookRecord {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddrBookRecord();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.threadID = reader.readBytes();
                    break;
                case 2:
                    message.peerID = reader.readBytes();
                    break;
                case 3:
                    reader.readMessage(message.addrs, () => pb_1.Message.addToRepeatedWrapperField(message, 3, AddrBookRecord.AddrEntry.deserialize(reader), AddrBookRecord.AddrEntry));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): AddrBookRecord {
        return AddrBookRecord.deserialize(bytes);
    }
}
export namespace AddrBookRecord {
    export class AddrEntry extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            addr?: Uint8Array;
            expiry?: number;
            ttl?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("addr" in data && data.addr != undefined) {
                    this.addr = data.addr;
                }
                if ("expiry" in data && data.expiry != undefined) {
                    this.expiry = data.expiry;
                }
                if ("ttl" in data && data.ttl != undefined) {
                    this.ttl = data.ttl;
                }
            }
        }
        get addr() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array()) as Uint8Array;
        }
        set addr(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get expiry() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set expiry(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get ttl() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set ttl(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            addr?: Uint8Array;
            expiry?: number;
            ttl?: number;
        }): AddrEntry {
            const message = new AddrEntry({});
            if (data.addr != null) {
                message.addr = data.addr;
            }
            if (data.expiry != null) {
                message.expiry = data.expiry;
            }
            if (data.ttl != null) {
                message.ttl = data.ttl;
            }
            return message;
        }
        toObject() {
            const data: {
                addr?: Uint8Array;
                expiry?: number;
                ttl?: number;
            } = {};
            if (this.addr != null) {
                data.addr = this.addr;
            }
            if (this.expiry != null) {
                data.expiry = this.expiry;
            }
            if (this.ttl != null) {
                data.ttl = this.ttl;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.addr.length)
                writer.writeBytes(1, this.addr);
            if (this.expiry != 0)
                writer.writeInt64(2, this.expiry);
            if (this.ttl != 0)
                writer.writeInt64(3, this.ttl);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddrEntry {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddrEntry();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.addr = reader.readBytes();
                        break;
                    case 2:
                        message.expiry = reader.readInt64();
                        break;
                    case 3:
                        message.ttl = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AddrEntry {
            return AddrEntry.deserialize(bytes);
        }
    }
}
export class HeadBookRecord extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        heads?: HeadBookRecord.HeadEntry[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("heads" in data && data.heads != undefined) {
                this.heads = data.heads;
            }
        }
    }
    get heads() {
        return pb_1.Message.getRepeatedWrapperField(this, HeadBookRecord.HeadEntry, 1) as HeadBookRecord.HeadEntry[];
    }
    set heads(value: HeadBookRecord.HeadEntry[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        heads?: ReturnType<typeof HeadBookRecord.HeadEntry.prototype.toObject>[];
    }): HeadBookRecord {
        const message = new HeadBookRecord({});
        if (data.heads != null) {
            message.heads = data.heads.map(item => HeadBookRecord.HeadEntry.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            heads?: ReturnType<typeof HeadBookRecord.HeadEntry.prototype.toObject>[];
        } = {};
        if (this.heads != null) {
            data.heads = this.heads.map((item: HeadBookRecord.HeadEntry) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.heads.length)
            writer.writeRepeatedMessage(1, this.heads, (item: HeadBookRecord.HeadEntry) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HeadBookRecord {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HeadBookRecord();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.heads, () => pb_1.Message.addToRepeatedWrapperField(message, 1, HeadBookRecord.HeadEntry.deserialize(reader), HeadBookRecord.HeadEntry));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): HeadBookRecord {
        return HeadBookRecord.deserialize(bytes);
    }
}
export namespace HeadBookRecord {
    export class HeadEntry extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            cid?: Uint8Array;
            counter?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("cid" in data && data.cid != undefined) {
                    this.cid = data.cid;
                }
                if ("counter" in data && data.counter != undefined) {
                    this.counter = data.counter;
                }
            }
        }
        get cid() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array()) as Uint8Array;
        }
        set cid(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get counter() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set counter(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            cid?: Uint8Array;
            counter?: number;
        }): HeadEntry {
            const message = new HeadEntry({});
            if (data.cid != null) {
                message.cid = data.cid;
            }
            if (data.counter != null) {
                message.counter = data.counter;
            }
            return message;
        }
        toObject() {
            const data: {
                cid?: Uint8Array;
                counter?: number;
            } = {};
            if (this.cid != null) {
                data.cid = this.cid;
            }
            if (this.counter != null) {
                data.counter = this.counter;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.cid.length)
                writer.writeBytes(1, this.cid);
            if (this.counter != 0)
                writer.writeInt64(2, this.counter);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HeadEntry {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new HeadEntry();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.cid = reader.readBytes();
                        break;
                    case 2:
                        message.counter = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): HeadEntry {
            return HeadEntry.deserialize(bytes);
        }
    }
}
