/**
 * @fileoverview gRPC-Web generated client stub for dcnet.pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: dcnet.proto

/* eslint-disable */
// @ts-nocheck

import * as grpcWeb from 'grpc-web'

import dcnet_pb from './dcnet_pb' // proto import: "dcnet.proto"

export class ServiceClient {
  client_: grpcWeb.AbstractClientBase
  hostname_: string
  credentials_: null | { [index: string]: string }
  options_: null | { [index: string]: any }

  constructor(
    hostname: string,
    credentials?: null | { [index: string]: string },
    options?: null | { [index: string]: any }
  ) {
    if (!options) options = {}
    if (!credentials) credentials = {}
    options['format'] = 'text'

    this.client_ = new grpcWeb.GrpcWebClientBase(options)
    this.hostname_ = hostname.replace(/\/+$/, '')
    this.credentials_ = credentials
    this.options_ = options
  }

  methodDescriptorStoreThreadToPeer = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/StoreThreadToPeer',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.StoreThreadRequest,
    dcnet_pb.StoreThreadReply,
    (request: dcnet_pb.StoreThreadRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.StoreThreadReply.deserializeBinary
  )

  storeThreadToPeer(
    request: dcnet_pb.StoreThreadRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.StoreThreadReply>

  storeThreadToPeer(
    request: dcnet_pb.StoreThreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.StoreThreadReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.StoreThreadReply>

  storeThreadToPeer(
    request: dcnet_pb.StoreThreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.StoreThreadReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/StoreThreadToPeer',
        request,
        metadata || {},
        this.methodDescriptorStoreThreadToPeer,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/StoreThreadToPeer',
      request,
      metadata || {},
      this.methodDescriptorStoreThreadToPeer
    )
  }

  methodDescriptorStoreFileToPeer = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/StoreFileToPeer',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.StroeFileToPeerRequest,
    dcnet_pb.StroeFileToPeerReply,
    (request: dcnet_pb.StroeFileToPeerRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.StroeFileToPeerReply.deserializeBinary
  )

  storeFileToPeer(
    request: dcnet_pb.StroeFileToPeerRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.StroeFileToPeerReply>

  storeFileToPeer(
    request: dcnet_pb.StroeFileToPeerRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.StroeFileToPeerReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.StroeFileToPeerReply>

  storeFileToPeer(
    request: dcnet_pb.StroeFileToPeerRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.StroeFileToPeerReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/StoreFileToPeer',
        request,
        metadata || {},
        this.methodDescriptorStoreFileToPeer,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/StoreFileToPeer',
      request,
      metadata || {},
      this.methodDescriptorStoreFileToPeer
    )
  }

  methodDescriptorAccountBindBackup = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountBindBackup',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountDealBackupRequest,
    dcnet_pb.AccountDealBackupReply,
    (request: dcnet_pb.AccountDealBackupRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountDealBackupReply.deserializeBinary
  )

  accountBindBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountDealBackupReply>

  accountBindBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealBackupReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountDealBackupReply>

  accountBindBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealBackupReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountBindBackup',
        request,
        metadata || {},
        this.methodDescriptorAccountBindBackup,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountBindBackup',
      request,
      metadata || {},
      this.methodDescriptorAccountBindBackup
    )
  }

  methodDescriptorAccountInfoModifyBackup = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountInfoModifyBackup',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountDealBackupRequest,
    dcnet_pb.AccountDealBackupReply,
    (request: dcnet_pb.AccountDealBackupRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountDealBackupReply.deserializeBinary
  )

  accountInfoModifyBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountDealBackupReply>

  accountInfoModifyBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealBackupReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountDealBackupReply>

  accountInfoModifyBackup(
    request: dcnet_pb.AccountDealBackupRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealBackupReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountInfoModifyBackup',
        request,
        metadata || {},
        this.methodDescriptorAccountInfoModifyBackup,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountInfoModifyBackup',
      request,
      metadata || {},
      this.methodDescriptorAccountInfoModifyBackup
    )
  }

  methodDescriptorOnlineStatusCheck = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/OnlineStatusCheck',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.OnlineStatusCheckRequest,
    dcnet_pb.OnlineStatusCheckReply,
    (request: dcnet_pb.OnlineStatusCheckRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.OnlineStatusCheckReply.deserializeBinary
  )

  onlineStatusCheck(
    request: dcnet_pb.OnlineStatusCheckRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.OnlineStatusCheckReply>

  onlineStatusCheck(
    request: dcnet_pb.OnlineStatusCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.OnlineStatusCheckReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.OnlineStatusCheckReply>

  onlineStatusCheck(
    request: dcnet_pb.OnlineStatusCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.OnlineStatusCheckReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/OnlineStatusCheck',
        request,
        metadata || {},
        this.methodDescriptorOnlineStatusCheck,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/OnlineStatusCheck',
      request,
      metadata || {},
      this.methodDescriptorOnlineStatusCheck
    )
  }

  methodDescriptorTeeReportVerify = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/TeeReportVerify',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.TeeReportVerifyRequest,
    dcnet_pb.TeeReportVerifyReply,
    (request: dcnet_pb.TeeReportVerifyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.TeeReportVerifyReply.deserializeBinary
  )

  teeReportVerify(
    request: dcnet_pb.TeeReportVerifyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.TeeReportVerifyReply>

  teeReportVerify(
    request: dcnet_pb.TeeReportVerifyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.TeeReportVerifyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.TeeReportVerifyReply>

  teeReportVerify(
    request: dcnet_pb.TeeReportVerifyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.TeeReportVerifyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/TeeReportVerify',
        request,
        metadata || {},
        this.methodDescriptorTeeReportVerify,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/TeeReportVerify',
      request,
      metadata || {},
      this.methodDescriptorTeeReportVerify
    )
  }

  methodDescriptorLocalFileCheck = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/LocalFileCheck',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.LocalFileCheckRequest,
    dcnet_pb.LocalFileCheckReply,
    (request: dcnet_pb.LocalFileCheckRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.LocalFileCheckReply.deserializeBinary
  )

  localFileCheck(
    request: dcnet_pb.LocalFileCheckRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.LocalFileCheckReply>

  localFileCheck(
    request: dcnet_pb.LocalFileCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.LocalFileCheckReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.LocalFileCheckReply>

  localFileCheck(
    request: dcnet_pb.LocalFileCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.LocalFileCheckReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/LocalFileCheck',
        request,
        metadata || {},
        this.methodDescriptorLocalFileCheck,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/LocalFileCheck',
      request,
      metadata || {},
      this.methodDescriptorLocalFileCheck
    )
  }

  methodDescriptorGetPeersWithSid = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetPeersWithSid',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetPeersWithSidRequest,
    dcnet_pb.GetPeersWithSidReply,
    (request: dcnet_pb.GetPeersWithSidRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetPeersWithSidReply.deserializeBinary
  )

  getPeersWithSid(
    request: dcnet_pb.GetPeersWithSidRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetPeersWithSidReply>

  getPeersWithSid(
    request: dcnet_pb.GetPeersWithSidRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetPeersWithSidReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetPeersWithSidReply>

  getPeersWithSid(
    request: dcnet_pb.GetPeersWithSidRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetPeersWithSidReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetPeersWithSid',
        request,
        metadata || {},
        this.methodDescriptorGetPeersWithSid,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetPeersWithSid',
      request,
      metadata || {},
      this.methodDescriptorGetPeersWithSid
    )
  }

  methodDescriptorGetPeersWithAccountHash = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetPeersWithAccountHash',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetPeersWithAccountHashRequest,
    dcnet_pb.GetPeersWithAccountHashReply,
    (request: dcnet_pb.GetPeersWithAccountHashRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetPeersWithAccountHashReply.deserializeBinary
  )

  getPeersWithAccountHash(
    request: dcnet_pb.GetPeersWithAccountHashRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetPeersWithAccountHashReply>

  getPeersWithAccountHash(
    request: dcnet_pb.GetPeersWithAccountHashRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetPeersWithAccountHashReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetPeersWithAccountHashReply>

  getPeersWithAccountHash(
    request: dcnet_pb.GetPeersWithAccountHashRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetPeersWithAccountHashReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetPeersWithAccountHash',
        request,
        metadata || {},
        this.methodDescriptorGetPeersWithAccountHash,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetPeersWithAccountHash',
      request,
      metadata || {},
      this.methodDescriptorGetPeersWithAccountHash
    )
  }

  methodDescriptorLocalAccountInfoCheck = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/LocalAccountInfoCheck',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.LocalAccountInfoCheckRequest,
    dcnet_pb.LocalAccountInfoCheckReply,
    (request: dcnet_pb.LocalAccountInfoCheckRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.LocalAccountInfoCheckReply.deserializeBinary
  )

  localAccountInfoCheck(
    request: dcnet_pb.LocalAccountInfoCheckRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.LocalAccountInfoCheckReply>

  localAccountInfoCheck(
    request: dcnet_pb.LocalAccountInfoCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.LocalAccountInfoCheckReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.LocalAccountInfoCheckReply>

  localAccountInfoCheck(
    request: dcnet_pb.LocalAccountInfoCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.LocalAccountInfoCheckReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/LocalAccountInfoCheck',
        request,
        metadata || {},
        this.methodDescriptorLocalAccountInfoCheck,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/LocalAccountInfoCheck',
      request,
      metadata || {},
      this.methodDescriptorLocalAccountInfoCheck
    )
  }

  methodDescriptorAccountInfoSync = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountInfoSync',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountInfoSyncRequest,
    dcnet_pb.AccountInfoSyncReply,
    (request: dcnet_pb.AccountInfoSyncRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountInfoSyncReply.deserializeBinary
  )

  accountInfoSync(
    request: dcnet_pb.AccountInfoSyncRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountInfoSyncReply>

  accountInfoSync(
    request: dcnet_pb.AccountInfoSyncRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountInfoSyncReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountInfoSyncReply>

  accountInfoSync(
    request: dcnet_pb.AccountInfoSyncRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountInfoSyncReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountInfoSync',
        request,
        metadata || {},
        this.methodDescriptorAccountInfoSync,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountInfoSync',
      request,
      metadata || {},
      this.methodDescriptorAccountInfoSync
    )
  }

  methodDescriptorSetEncryptKeyWithScan = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SetEncryptKeyWithScan',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.SetEncryptKeyWithScanRequest,
    dcnet_pb.SetEncryptKeyWithScanReply,
    (request: dcnet_pb.SetEncryptKeyWithScanRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.SetEncryptKeyWithScanReply.deserializeBinary
  )

  setEncryptKeyWithScan(
    request: dcnet_pb.SetEncryptKeyWithScanRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.SetEncryptKeyWithScanReply>

  setEncryptKeyWithScan(
    request: dcnet_pb.SetEncryptKeyWithScanRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.SetEncryptKeyWithScanReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.SetEncryptKeyWithScanReply>

  setEncryptKeyWithScan(
    request: dcnet_pb.SetEncryptKeyWithScanRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.SetEncryptKeyWithScanReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SetEncryptKeyWithScan',
        request,
        metadata || {},
        this.methodDescriptorSetEncryptKeyWithScan,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SetEncryptKeyWithScan',
      request,
      metadata || {},
      this.methodDescriptorSetEncryptKeyWithScan
    )
  }

  methodDescriptorGetEncryptKeyWithScan = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetEncryptKeyWithScan',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetEncryptKeyWithScanRequest,
    dcnet_pb.GetEncryptKeyWithScanReply,
    (request: dcnet_pb.GetEncryptKeyWithScanRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetEncryptKeyWithScanReply.deserializeBinary
  )

  getEncryptKeyWithScan(
    request: dcnet_pb.GetEncryptKeyWithScanRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetEncryptKeyWithScanReply>

  getEncryptKeyWithScan(
    request: dcnet_pb.GetEncryptKeyWithScanRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetEncryptKeyWithScanReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetEncryptKeyWithScanReply>

  getEncryptKeyWithScan(
    request: dcnet_pb.GetEncryptKeyWithScanRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetEncryptKeyWithScanReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetEncryptKeyWithScan',
        request,
        metadata || {},
        this.methodDescriptorGetEncryptKeyWithScan,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetEncryptKeyWithScan',
      request,
      metadata || {},
      this.methodDescriptorGetEncryptKeyWithScan
    )
  }

  methodDescriptorRequestRandEncryptKey = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/RequestRandEncryptKey',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.RequestRandEncryptKeyRequest,
    dcnet_pb.RequestRandEncryptKeyReply,
    (request: dcnet_pb.RequestRandEncryptKeyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.RequestRandEncryptKeyReply.deserializeBinary
  )

  requestRandEncryptKey(
    request: dcnet_pb.RequestRandEncryptKeyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.RequestRandEncryptKeyReply>

  requestRandEncryptKey(
    request: dcnet_pb.RequestRandEncryptKeyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.RequestRandEncryptKeyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.RequestRandEncryptKeyReply>

  requestRandEncryptKey(
    request: dcnet_pb.RequestRandEncryptKeyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.RequestRandEncryptKeyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/RequestRandEncryptKey',
        request,
        metadata || {},
        this.methodDescriptorRequestRandEncryptKey,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/RequestRandEncryptKey',
      request,
      metadata || {},
      this.methodDescriptorRequestRandEncryptKey
    )
  }

  methodDescriptorGetEncryptKey = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetEncryptKey',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetEncryptKeyRequest,
    dcnet_pb.GetEncryptKeyReply,
    (request: dcnet_pb.GetEncryptKeyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetEncryptKeyReply.deserializeBinary
  )

  getEncryptKey(
    request: dcnet_pb.GetEncryptKeyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetEncryptKeyReply>

  getEncryptKey(
    request: dcnet_pb.GetEncryptKeyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetEncryptKeyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetEncryptKeyReply>

  getEncryptKey(
    request: dcnet_pb.GetEncryptKeyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetEncryptKeyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetEncryptKey',
        request,
        metadata || {},
        this.methodDescriptorGetEncryptKey,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetEncryptKey',
      request,
      metadata || {},
      this.methodDescriptorGetEncryptKey
    )
  }

  methodDescriptorGetHostID = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetHostID',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetHostIDRequest,
    dcnet_pb.GetHostIDReply,
    (request: dcnet_pb.GetHostIDRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetHostIDReply.deserializeBinary
  )

  getHostID(
    request: dcnet_pb.GetHostIDRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetHostIDReply>

  getHostID(
    request: dcnet_pb.GetHostIDRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetHostIDReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetHostIDReply>

  getHostID(
    request: dcnet_pb.GetHostIDRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetHostIDReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetHostID',
        request,
        metadata || {},
        this.methodDescriptorGetHostID,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetHostID',
      request,
      metadata || {},
      this.methodDescriptorGetHostID
    )
  }

  methodDescriptorCreateThread = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/CreateThread',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.CreateThreadRequest,
    dcnet_pb.ThreadInfoReply,
    (request: dcnet_pb.CreateThreadRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ThreadInfoReply.deserializeBinary
  )

  createThread(
    request: dcnet_pb.CreateThreadRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ThreadInfoReply>

  createThread(
    request: dcnet_pb.CreateThreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadInfoReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ThreadInfoReply>

  createThread(
    request: dcnet_pb.CreateThreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadInfoReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/CreateThread',
        request,
        metadata || {},
        this.methodDescriptorCreateThread,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/CreateThread',
      request,
      metadata || {},
      this.methodDescriptorCreateThread
    )
  }

  methodDescriptorRequestThreadID = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/RequestThreadID',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.ThreadIDRequest,
    dcnet_pb.ThreadIDReply,
    (request: dcnet_pb.ThreadIDRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ThreadIDReply.deserializeBinary
  )

  requestThreadID(
    request: dcnet_pb.ThreadIDRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ThreadIDReply>

  requestThreadID(
    request: dcnet_pb.ThreadIDRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadIDReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ThreadIDReply>

  requestThreadID(
    request: dcnet_pb.ThreadIDRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadIDReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/RequestThreadID',
        request,
        metadata || {},
        this.methodDescriptorRequestThreadID,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/RequestThreadID',
      request,
      metadata || {},
      this.methodDescriptorRequestThreadID
    )
  }

  methodDescriptorAddLogToThread = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddLogToThread',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddLogToThreadRequest,
    dcnet_pb.AddLogToThreadReply,
    (request: dcnet_pb.AddLogToThreadRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddLogToThreadReply.deserializeBinary
  )

  addLogToThread(
    request: dcnet_pb.AddLogToThreadRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddLogToThreadReply>

  addLogToThread(
    request: dcnet_pb.AddLogToThreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddLogToThreadReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddLogToThreadReply>

  addLogToThread(
    request: dcnet_pb.AddLogToThreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddLogToThreadReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddLogToThread',
        request,
        metadata || {},
        this.methodDescriptorAddLogToThread,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddLogToThread',
      request,
      metadata || {},
      this.methodDescriptorAddLogToThread
    )
  }

  methodDescriptorGetThreadUsedSpace = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetThreadUsedSpace',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetThreadUsedSpaceRequest,
    dcnet_pb.GetThreadUsedSpaceReply,
    (request: dcnet_pb.GetThreadUsedSpaceRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetThreadUsedSpaceReply.deserializeBinary
  )

  getThreadUsedSpace(
    request: dcnet_pb.GetThreadUsedSpaceRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetThreadUsedSpaceReply>

  getThreadUsedSpace(
    request: dcnet_pb.GetThreadUsedSpaceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetThreadUsedSpaceReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetThreadUsedSpaceReply>

  getThreadUsedSpace(
    request: dcnet_pb.GetThreadUsedSpaceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetThreadUsedSpaceReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetThreadUsedSpace',
        request,
        metadata || {},
        this.methodDescriptorGetThreadUsedSpace,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetThreadUsedSpace',
      request,
      metadata || {},
      this.methodDescriptorGetThreadUsedSpace
    )
  }

  methodDescriptorAddThreadToPeer = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddThreadToPeer',
    grpcWeb.MethodType.SERVER_STREAMING,
    dcnet_pb.AddThreadToPeerRequest,
    dcnet_pb.AddThreadToPeerReply,
    (request: dcnet_pb.AddThreadToPeerRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddThreadToPeerReply.deserializeBinary
  )

  addThreadToPeer(
    request: dcnet_pb.AddThreadToPeerRequest,
    metadata?: grpcWeb.Metadata
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddThreadToPeerReply> {
    return this.client_.serverStreaming(
      this.hostname_ + '/dcnet.pb.Service/AddThreadToPeer',
      request,
      metadata || {},
      this.methodDescriptorAddThreadToPeer
    )
  }

  methodDescriptorGetThread = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetThread',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetThreadRequest,
    dcnet_pb.ThreadInfoReply,
    (request: dcnet_pb.GetThreadRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ThreadInfoReply.deserializeBinary
  )

  getThread(
    request: dcnet_pb.GetThreadRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ThreadInfoReply>

  getThread(
    request: dcnet_pb.GetThreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadInfoReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ThreadInfoReply>

  getThread(
    request: dcnet_pb.GetThreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ThreadInfoReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetThread',
        request,
        metadata || {},
        this.methodDescriptorGetThread,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetThread',
      request,
      metadata || {},
      this.methodDescriptorGetThread
    )
  }

  methodDescriptorDeleteThread = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteThread',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteThreadRequest,
    dcnet_pb.DeleteThreadReply,
    (request: dcnet_pb.DeleteThreadRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteThreadReply.deserializeBinary
  )

  deleteThread(
    request: dcnet_pb.DeleteThreadRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteThreadReply>

  deleteThread(
    request: dcnet_pb.DeleteThreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteThreadReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteThreadReply>

  deleteThread(
    request: dcnet_pb.DeleteThreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteThreadReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteThread',
        request,
        metadata || {},
        this.methodDescriptorDeleteThread,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteThread',
      request,
      metadata || {},
      this.methodDescriptorDeleteThread
    )
  }

  methodDescriptorAddThreadSpace = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddThreadSpace',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddThreadSpaceRequest,
    dcnet_pb.AddThreadSpaceReply,
    (request: dcnet_pb.AddThreadSpaceRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddThreadSpaceReply.deserializeBinary
  )

  addThreadSpace(
    request: dcnet_pb.AddThreadSpaceRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddThreadSpaceReply>

  addThreadSpace(
    request: dcnet_pb.AddThreadSpaceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddThreadSpaceReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddThreadSpaceReply>

  addThreadSpace(
    request: dcnet_pb.AddThreadSpaceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddThreadSpaceReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddThreadSpace',
        request,
        metadata || {},
        this.methodDescriptorAddThreadSpace,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddThreadSpace',
      request,
      metadata || {},
      this.methodDescriptorAddThreadSpace
    )
  }

  methodDescriptorStoreFile = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/StoreFile',
    grpcWeb.MethodType.SERVER_STREAMING,
    dcnet_pb.StroeFileRequest,
    dcnet_pb.StroeFileReply,
    (request: dcnet_pb.StroeFileRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.StroeFileReply.deserializeBinary
  )

  storeFile(
    request: dcnet_pb.StroeFileRequest,
    metadata?: grpcWeb.Metadata
  ): grpcWeb.ClientReadableStream<dcnet_pb.StroeFileReply> {
    return this.client_.serverStreaming(
      this.hostname_ + '/dcnet.pb.Service/StoreFile',
      request,
      metadata || {},
      this.methodDescriptorStoreFile
    )
  }

  methodDescriptorStoreFolder = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/StoreFolder',
    grpcWeb.MethodType.SERVER_STREAMING,
    dcnet_pb.StoreFolderRequest,
    dcnet_pb.StoreFolderReply,
    (request: dcnet_pb.StoreFolderRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.StoreFolderReply.deserializeBinary
  )

  storeFolder(
    request: dcnet_pb.StoreFolderRequest,
    metadata?: grpcWeb.Metadata
  ): grpcWeb.ClientReadableStream<dcnet_pb.StoreFolderReply> {
    return this.client_.serverStreaming(
      this.hostname_ + '/dcnet.pb.Service/StoreFolder',
      request,
      metadata || {},
      this.methodDescriptorStoreFolder
    )
  }

  methodDescriptorDeleteFile = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteFile',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteFileRequest,
    dcnet_pb.DeleteFileReply,
    (request: dcnet_pb.DeleteFileRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteFileReply.deserializeBinary
  )

  deleteFile(
    request: dcnet_pb.DeleteFileRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteFileReply>

  deleteFile(
    request: dcnet_pb.DeleteFileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteFileReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteFileReply>

  deleteFile(
    request: dcnet_pb.DeleteFileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteFileReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteFile',
        request,
        metadata || {},
        this.methodDescriptorDeleteFile,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteFile',
      request,
      metadata || {},
      this.methodDescriptorDeleteFile
    )
  }

  methodDescriptorAccountBind = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountBind',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountDealRequest,
    dcnet_pb.AccountDealReply,
    (request: dcnet_pb.AccountDealRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountDealReply.deserializeBinary
  )

  accountBind(
    request: dcnet_pb.AccountDealRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountDealReply>

  accountBind(
    request: dcnet_pb.AccountDealRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountDealReply>

  accountBind(
    request: dcnet_pb.AccountDealRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountBind',
        request,
        metadata || {},
        this.methodDescriptorAccountBind,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountBind',
      request,
      metadata || {},
      this.methodDescriptorAccountBind
    )
  }

  methodDescriptorAccountInfoModify = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountInfoModify',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountDealRequest,
    dcnet_pb.AccountDealReply,
    (request: dcnet_pb.AccountDealRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountDealReply.deserializeBinary
  )

  accountInfoModify(
    request: dcnet_pb.AccountDealRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountDealReply>

  accountInfoModify(
    request: dcnet_pb.AccountDealRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountDealReply>

  accountInfoModify(
    request: dcnet_pb.AccountDealRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountDealReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountInfoModify',
        request,
        metadata || {},
        this.methodDescriptorAccountInfoModify,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountInfoModify',
      request,
      metadata || {},
      this.methodDescriptorAccountInfoModify
    )
  }

  methodDescriptorAccountLogin = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AccountLogin',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AccountLoginRequest,
    dcnet_pb.AccountLoginReply,
    (request: dcnet_pb.AccountLoginRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AccountLoginReply.deserializeBinary
  )

  accountLogin(
    request: dcnet_pb.AccountLoginRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AccountLoginReply>

  accountLogin(
    request: dcnet_pb.AccountLoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AccountLoginReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AccountLoginReply>

  accountLogin(
    request: dcnet_pb.AccountLoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AccountLoginReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AccountLogin',
        request,
        metadata || {},
        this.methodDescriptorAccountLogin,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AccountLogin',
      request,
      metadata || {},
      this.methodDescriptorAccountLogin
    )
  }

  methodDescriptorTransferAccount = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/TransferAccount',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.TransferAccountRequest,
    dcnet_pb.TransferAccountReply,
    (request: dcnet_pb.TransferAccountRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.TransferAccountReply.deserializeBinary
  )

  transferAccount(
    request: dcnet_pb.TransferAccountRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.TransferAccountReply>

  transferAccount(
    request: dcnet_pb.TransferAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.TransferAccountReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.TransferAccountReply>

  transferAccount(
    request: dcnet_pb.TransferAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.TransferAccountReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/TransferAccount',
        request,
        metadata || {},
        this.methodDescriptorTransferAccount,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/TransferAccount',
      request,
      metadata || {},
      this.methodDescriptorTransferAccount
    )
  }

  methodDescriptorAddSubPubkey = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddSubPubkey',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddSubPubkeyRequest,
    dcnet_pb.AddSubPubkeyReply,
    (request: dcnet_pb.AddSubPubkeyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddSubPubkeyReply.deserializeBinary
  )

  addSubPubkey(
    request: dcnet_pb.AddSubPubkeyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddSubPubkeyReply>

  addSubPubkey(
    request: dcnet_pb.AddSubPubkeyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddSubPubkeyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddSubPubkeyReply>

  addSubPubkey(
    request: dcnet_pb.AddSubPubkeyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddSubPubkeyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddSubPubkey',
        request,
        metadata || {},
        this.methodDescriptorAddSubPubkey,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddSubPubkey',
      request,
      metadata || {},
      this.methodDescriptorAddSubPubkey
    )
  }

  methodDescriptorDeleteSubPubkey = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteSubPubkey',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteSubPubkeyRequest,
    dcnet_pb.DeleteSubPubkeyReply,
    (request: dcnet_pb.DeleteSubPubkeyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteSubPubkeyReply.deserializeBinary
  )

  deleteSubPubkey(
    request: dcnet_pb.DeleteSubPubkeyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteSubPubkeyReply>

  deleteSubPubkey(
    request: dcnet_pb.DeleteSubPubkeyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteSubPubkeyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteSubPubkeyReply>

  deleteSubPubkey(
    request: dcnet_pb.DeleteSubPubkeyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteSubPubkeyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteSubPubkey',
        request,
        metadata || {},
        this.methodDescriptorDeleteSubPubkey,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteSubPubkey',
      request,
      metadata || {},
      this.methodDescriptorDeleteSubPubkey
    )
  }

  methodDescriptorBindAccessPeerToUser = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/BindAccessPeerToUser',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.BindAccessPeerToUserRequest,
    dcnet_pb.BindAccessPeerToUserReply,
    (request: dcnet_pb.BindAccessPeerToUserRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.BindAccessPeerToUserReply.deserializeBinary
  )

  bindAccessPeerToUser(
    request: dcnet_pb.BindAccessPeerToUserRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.BindAccessPeerToUserReply>

  bindAccessPeerToUser(
    request: dcnet_pb.BindAccessPeerToUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.BindAccessPeerToUserReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.BindAccessPeerToUserReply>

  bindAccessPeerToUser(
    request: dcnet_pb.BindAccessPeerToUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.BindAccessPeerToUserReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/BindAccessPeerToUser',
        request,
        metadata || {},
        this.methodDescriptorBindAccessPeerToUser,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/BindAccessPeerToUser',
      request,
      metadata || {},
      this.methodDescriptorBindAccessPeerToUser
    )
  }

  methodDescriptorSetUserDefaultDB = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SetUserDefaultDB',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.SetUserDefaultDBRequest,
    dcnet_pb.SetUserDefaultDBReply,
    (request: dcnet_pb.SetUserDefaultDBRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.SetUserDefaultDBReply.deserializeBinary
  )

  setUserDefaultDB(
    request: dcnet_pb.SetUserDefaultDBRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.SetUserDefaultDBReply>

  setUserDefaultDB(
    request: dcnet_pb.SetUserDefaultDBRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.SetUserDefaultDBReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.SetUserDefaultDBReply>

  setUserDefaultDB(
    request: dcnet_pb.SetUserDefaultDBRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.SetUserDefaultDBReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SetUserDefaultDB',
        request,
        metadata || {},
        this.methodDescriptorSetUserDefaultDB,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SetUserDefaultDB',
      request,
      metadata || {},
      this.methodDescriptorSetUserDefaultDB
    )
  }

  methodDescriptorSendMsgToUserBox = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SendMsgToUserBox',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.SendMsgToUserBoxRequest,
    dcnet_pb.SendMsgToUserBoxReply,
    (request: dcnet_pb.SendMsgToUserBoxRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.SendMsgToUserBoxReply.deserializeBinary
  )

  sendMsgToUserBox(
    request: dcnet_pb.SendMsgToUserBoxRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.SendMsgToUserBoxReply>

  sendMsgToUserBox(
    request: dcnet_pb.SendMsgToUserBoxRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.SendMsgToUserBoxReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.SendMsgToUserBoxReply>

  sendMsgToUserBox(
    request: dcnet_pb.SendMsgToUserBoxRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.SendMsgToUserBoxReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SendMsgToUserBox',
        request,
        metadata || {},
        this.methodDescriptorSendMsgToUserBox,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SendMsgToUserBox',
      request,
      metadata || {},
      this.methodDescriptorSendMsgToUserBox
    )
  }

  methodDescriptorGetToUserBoxAuth = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetToUserBoxAuth',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetToUserBoxAuthRequest,
    dcnet_pb.GetToUserBoxAuthReply,
    (request: dcnet_pb.GetToUserBoxAuthRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetToUserBoxAuthReply.deserializeBinary
  )

  getToUserBoxAuth(
    request: dcnet_pb.GetToUserBoxAuthRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetToUserBoxAuthReply>

  getToUserBoxAuth(
    request: dcnet_pb.GetToUserBoxAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetToUserBoxAuthReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetToUserBoxAuthReply>

  getToUserBoxAuth(
    request: dcnet_pb.GetToUserBoxAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetToUserBoxAuthReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetToUserBoxAuth',
        request,
        metadata || {},
        this.methodDescriptorGetToUserBoxAuth,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetToUserBoxAuth',
      request,
      metadata || {},
      this.methodDescriptorGetToUserBoxAuth
    )
  }

  methodDescriptorGetMsgFromUserBox = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetMsgFromUserBox',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetMsgFromUserBoxRequest,
    dcnet_pb.GetMsgFromUserBoxReply,
    (request: dcnet_pb.GetMsgFromUserBoxRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetMsgFromUserBoxReply.deserializeBinary
  )

  getMsgFromUserBox(
    request: dcnet_pb.GetMsgFromUserBoxRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetMsgFromUserBoxReply>

  getMsgFromUserBox(
    request: dcnet_pb.GetMsgFromUserBoxRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetMsgFromUserBoxReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetMsgFromUserBoxReply>

  getMsgFromUserBox(
    request: dcnet_pb.GetMsgFromUserBoxRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetMsgFromUserBoxReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetMsgFromUserBox',
        request,
        metadata || {},
        this.methodDescriptorGetMsgFromUserBox,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetMsgFromUserBox',
      request,
      metadata || {},
      this.methodDescriptorGetMsgFromUserBox
    )
  }

  methodDescriptorReportSpamMsg = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/ReportSpamMsg',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.ReportSpamMsgRequest,
    dcnet_pb.ReportSpamMsgReply,
    (request: dcnet_pb.ReportSpamMsgRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ReportSpamMsgReply.deserializeBinary
  )

  reportSpamMsg(
    request: dcnet_pb.ReportSpamMsgRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ReportSpamMsgReply>

  reportSpamMsg(
    request: dcnet_pb.ReportSpamMsgRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ReportSpamMsgReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ReportSpamMsgReply>

  reportSpamMsg(
    request: dcnet_pb.ReportSpamMsgRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ReportSpamMsgReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/ReportSpamMsg',
        request,
        metadata || {},
        this.methodDescriptorReportSpamMsg,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/ReportSpamMsg',
      request,
      metadata || {},
      this.methodDescriptorReportSpamMsg
    )
  }

  methodDescriptorValidToken = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/ValidToken',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.ValidTokenRequest,
    dcnet_pb.ValidTokenReply,
    (request: dcnet_pb.ValidTokenRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ValidTokenReply.deserializeBinary
  )

  validToken(
    request: dcnet_pb.ValidTokenRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ValidTokenReply>

  validToken(
    request: dcnet_pb.ValidTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ValidTokenReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ValidTokenReply>

  validToken(
    request: dcnet_pb.ValidTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ValidTokenReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/ValidToken',
        request,
        metadata || {},
        this.methodDescriptorValidToken,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/ValidToken',
      request,
      metadata || {},
      this.methodDescriptorValidToken
    )
  }

  methodDescriptorGetUserClientPeers = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetUserClientPeers',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetUserClientPeersRequest,
    dcnet_pb.GetUserClientPeersReply,
    (request: dcnet_pb.GetUserClientPeersRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetUserClientPeersReply.deserializeBinary
  )

  getUserClientPeers(
    request: dcnet_pb.GetUserClientPeersRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetUserClientPeersReply>

  getUserClientPeers(
    request: dcnet_pb.GetUserClientPeersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetUserClientPeersReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetUserClientPeersReply>

  getUserClientPeers(
    request: dcnet_pb.GetUserClientPeersRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetUserClientPeersReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetUserClientPeers',
        request,
        metadata || {},
        this.methodDescriptorGetUserClientPeers,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetUserClientPeers',
      request,
      metadata || {},
      this.methodDescriptorGetUserClientPeers
    )
  }

  methodDescriptorSetCacheKey = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SetCacheKey',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.SetCacheKeyRequest,
    dcnet_pb.SetCacheKeyReply,
    (request: dcnet_pb.SetCacheKeyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.SetCacheKeyReply.deserializeBinary
  )

  setCacheKey(
    request: dcnet_pb.SetCacheKeyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.SetCacheKeyReply>

  setCacheKey(
    request: dcnet_pb.SetCacheKeyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.SetCacheKeyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.SetCacheKeyReply>

  setCacheKey(
    request: dcnet_pb.SetCacheKeyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.SetCacheKeyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SetCacheKey',
        request,
        metadata || {},
        this.methodDescriptorSetCacheKey,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SetCacheKey',
      request,
      metadata || {},
      this.methodDescriptorSetCacheKey
    )
  }

  methodDescriptorGetCacheValue = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetCacheValue',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetCacheValueRequest,
    dcnet_pb.GetCacheValueReply,
    (request: dcnet_pb.GetCacheValueRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetCacheValueReply.deserializeBinary
  )

  getCacheValue(
    request: dcnet_pb.GetCacheValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetCacheValueReply>

  getCacheValue(
    request: dcnet_pb.GetCacheValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetCacheValueReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetCacheValueReply>

  getCacheValue(
    request: dcnet_pb.GetCacheValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetCacheValueReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetCacheValue',
        request,
        metadata || {},
        this.methodDescriptorGetCacheValue,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetCacheValue',
      request,
      metadata || {},
      this.methodDescriptorGetCacheValue
    )
  }

  methodDescriptorAddCommentableObj = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddCommentableObj',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddCommentableObjRequest,
    dcnet_pb.AddCommentableObjReply,
    (request: dcnet_pb.AddCommentableObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddCommentableObjReply.deserializeBinary
  )

  addCommentableObj(
    request: dcnet_pb.AddCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddCommentableObjReply>

  addCommentableObj(
    request: dcnet_pb.AddCommentableObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddCommentableObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddCommentableObjReply>

  addCommentableObj(
    request: dcnet_pb.AddCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddCommentableObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddCommentableObj',
        request,
        metadata || {},
        this.methodDescriptorAddCommentableObj,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddCommentableObj',
      request,
      metadata || {},
      this.methodDescriptorAddCommentableObj
    )
  }

  methodDescriptorAddObjCommentSpace = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddObjCommentSpace',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddObjCommentSpaceRequest,
    dcnet_pb.AddObjCommentSpaceReply,
    (request: dcnet_pb.AddObjCommentSpaceRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddObjCommentSpaceReply.deserializeBinary
  )

  addObjCommentSpace(
    request: dcnet_pb.AddObjCommentSpaceRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddObjCommentSpaceReply>

  addObjCommentSpace(
    request: dcnet_pb.AddObjCommentSpaceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddObjCommentSpaceReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddObjCommentSpaceReply>

  addObjCommentSpace(
    request: dcnet_pb.AddObjCommentSpaceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddObjCommentSpaceReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddObjCommentSpace',
        request,
        metadata || {},
        this.methodDescriptorAddObjCommentSpace,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddObjCommentSpace',
      request,
      metadata || {},
      this.methodDescriptorAddObjCommentSpace
    )
  }

  methodDescriptorGetObjCommentSpace = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetObjCommentSpace',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetObjCommentSpaceRequest,
    dcnet_pb.GetObjCommentSpaceReply,
    (request: dcnet_pb.GetObjCommentSpaceRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetObjCommentSpaceReply.deserializeBinary
  )

  getObjCommentSpace(
    request: dcnet_pb.GetObjCommentSpaceRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetObjCommentSpaceReply>

  getObjCommentSpace(
    request: dcnet_pb.GetObjCommentSpaceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetObjCommentSpaceReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetObjCommentSpaceReply>

  getObjCommentSpace(
    request: dcnet_pb.GetObjCommentSpaceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetObjCommentSpaceReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetObjCommentSpace',
        request,
        metadata || {},
        this.methodDescriptorGetObjCommentSpace,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetObjCommentSpace',
      request,
      metadata || {},
      this.methodDescriptorGetObjCommentSpace
    )
  }

  methodDescriptorDeleteCommentableObj = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteCommentableObj',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteCommentableObjRequest,
    dcnet_pb.DeleteCommentableObjReply,
    (request: dcnet_pb.DeleteCommentableObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteCommentableObjReply.deserializeBinary
  )

  deleteCommentableObj(
    request: dcnet_pb.DeleteCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteCommentableObjReply>

  deleteCommentableObj(
    request: dcnet_pb.DeleteCommentableObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteCommentableObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteCommentableObjReply>

  deleteCommentableObj(
    request: dcnet_pb.DeleteCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteCommentableObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteCommentableObj',
        request,
        metadata || {},
        this.methodDescriptorDeleteCommentableObj,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteCommentableObj',
      request,
      metadata || {},
      this.methodDescriptorDeleteCommentableObj
    )
  }

  methodDescriptorReportMaliciousComment = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/ReportMaliciousComment',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.ReportMaliciousCommentRequest,
    dcnet_pb.ReportMaliciousCommentReply,
    (request: dcnet_pb.ReportMaliciousCommentRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ReportMaliciousCommentReply.deserializeBinary
  )

  reportMaliciousComment(
    request: dcnet_pb.ReportMaliciousCommentRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ReportMaliciousCommentReply>

  reportMaliciousComment(
    request: dcnet_pb.ReportMaliciousCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ReportMaliciousCommentReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ReportMaliciousCommentReply>

  reportMaliciousComment(
    request: dcnet_pb.ReportMaliciousCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ReportMaliciousCommentReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/ReportMaliciousComment',
        request,
        metadata || {},
        this.methodDescriptorReportMaliciousComment,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/ReportMaliciousComment',
      request,
      metadata || {},
      this.methodDescriptorReportMaliciousComment
    )
  }

  methodDescriptorSetObjCommentPublic = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SetObjCommentPublic',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.SetObjCommentPublicRequest,
    dcnet_pb.SetObjCommentPublicReply,
    (request: dcnet_pb.SetObjCommentPublicRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.SetObjCommentPublicReply.deserializeBinary
  )

  setObjCommentPublic(
    request: dcnet_pb.SetObjCommentPublicRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.SetObjCommentPublicReply>

  setObjCommentPublic(
    request: dcnet_pb.SetObjCommentPublicRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.SetObjCommentPublicReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.SetObjCommentPublicReply>

  setObjCommentPublic(
    request: dcnet_pb.SetObjCommentPublicRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.SetObjCommentPublicReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SetObjCommentPublic',
        request,
        metadata || {},
        this.methodDescriptorSetObjCommentPublic,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SetObjCommentPublic',
      request,
      metadata || {},
      this.methodDescriptorSetObjCommentPublic
    )
  }

  methodDescriptorAddUserOffChainSpace = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/AddUserOffChainSpace',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.AddUserOffChainSpaceRequest,
    dcnet_pb.AddUserOffChainSpaceReply,
    (request: dcnet_pb.AddUserOffChainSpaceRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.AddUserOffChainSpaceReply.deserializeBinary
  )

  addUserOffChainSpace(
    request: dcnet_pb.AddUserOffChainSpaceRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.AddUserOffChainSpaceReply>

  addUserOffChainSpace(
    request: dcnet_pb.AddUserOffChainSpaceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.AddUserOffChainSpaceReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.AddUserOffChainSpaceReply>

  addUserOffChainSpace(
    request: dcnet_pb.AddUserOffChainSpaceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.AddUserOffChainSpaceReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/AddUserOffChainSpace',
        request,
        metadata || {},
        this.methodDescriptorAddUserOffChainSpace,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/AddUserOffChainSpace',
      request,
      metadata || {},
      this.methodDescriptorAddUserOffChainSpace
    )
  }

  methodDescriptorPublishCommentToObj = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/PublishCommentToObj',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.PublishCommentToObjRequest,
    dcnet_pb.PublishCommentToObjReply,
    (request: dcnet_pb.PublishCommentToObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.PublishCommentToObjReply.deserializeBinary
  )

  publishCommentToObj(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.PublishCommentToObjReply>

  publishCommentToObj(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.PublishCommentToObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.PublishCommentToObjReply>

  publishCommentToObj(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.PublishCommentToObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/PublishCommentToObj',
        request,
        metadata || {},
        this.methodDescriptorPublishCommentToObj,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/PublishCommentToObj',
      request,
      metadata || {},
      this.methodDescriptorPublishCommentToObj
    )
  }

  methodDescriptorDeleteSelfComment = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteSelfComment',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteSelfCommentRequest,
    dcnet_pb.DeleteSelfCommentReply,
    (request: dcnet_pb.DeleteSelfCommentRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteSelfCommentReply.deserializeBinary
  )

  deleteSelfComment(
    request: dcnet_pb.DeleteSelfCommentRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteSelfCommentReply>

  deleteSelfComment(
    request: dcnet_pb.DeleteSelfCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteSelfCommentReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteSelfCommentReply>

  deleteSelfComment(
    request: dcnet_pb.DeleteSelfCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteSelfCommentReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteSelfComment',
        request,
        metadata || {},
        this.methodDescriptorDeleteSelfComment,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteSelfComment',
      request,
      metadata || {},
      this.methodDescriptorDeleteSelfComment
    )
  }

  methodDescriptorDeleteCommentToObj = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DeleteCommentToObj',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DeleteCommentToObjRequest,
    dcnet_pb.DeleteCommentToObjReply,
    (request: dcnet_pb.DeleteCommentToObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DeleteCommentToObjReply.deserializeBinary
  )

  deleteCommentToObj(
    request: dcnet_pb.DeleteCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DeleteCommentToObjReply>

  deleteCommentToObj(
    request: dcnet_pb.DeleteCommentToObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteCommentToObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DeleteCommentToObjReply>

  deleteCommentToObj(
    request: dcnet_pb.DeleteCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DeleteCommentToObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DeleteCommentToObj',
        request,
        metadata || {},
        this.methodDescriptorDeleteCommentToObj,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DeleteCommentToObj',
      request,
      metadata || {},
      this.methodDescriptorDeleteCommentToObj
    )
  }

  methodDescriptorGetCommentableObj = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetCommentableObj',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetCommentableObjRequest,
    dcnet_pb.GetCommentableObjReply,
    (request: dcnet_pb.GetCommentableObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetCommentableObjReply.deserializeBinary
  )

  getCommentableObj(
    request: dcnet_pb.GetCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetCommentableObjReply>

  getCommentableObj(
    request: dcnet_pb.GetCommentableObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetCommentableObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetCommentableObjReply>

  getCommentableObj(
    request: dcnet_pb.GetCommentableObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetCommentableObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetCommentableObj',
        request,
        metadata || {},
        this.methodDescriptorGetCommentableObj,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetCommentableObj',
      request,
      metadata || {},
      this.methodDescriptorGetCommentableObj
    )
  }

  methodDescriptorGetObjComments = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetObjComments',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetObjCommentsRequest,
    dcnet_pb.GetObjCommentsReply,
    (request: dcnet_pb.GetObjCommentsRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetObjCommentsReply.deserializeBinary
  )

  getObjComments(
    request: dcnet_pb.GetObjCommentsRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetObjCommentsReply>

  getObjComments(
    request: dcnet_pb.GetObjCommentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetObjCommentsReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetObjCommentsReply>

  getObjComments(
    request: dcnet_pb.GetObjCommentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetObjCommentsReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetObjComments',
        request,
        metadata || {},
        this.methodDescriptorGetObjComments,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetObjComments',
      request,
      metadata || {},
      this.methodDescriptorGetObjComments
    )
  }

  methodDescriptorGetUserComments = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/GetUserComments',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.GetUserCommentsRequest,
    dcnet_pb.GetUserCommentsReply,
    (request: dcnet_pb.GetUserCommentsRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.GetUserCommentsReply.deserializeBinary
  )

  getUserComments(
    request: dcnet_pb.GetUserCommentsRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.GetUserCommentsReply>

  getUserComments(
    request: dcnet_pb.GetUserCommentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.GetUserCommentsReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.GetUserCommentsReply>

  getUserComments(
    request: dcnet_pb.GetUserCommentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.GetUserCommentsReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/GetUserComments',
        request,
        metadata || {},
        this.methodDescriptorGetUserComments,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/GetUserComments',
      request,
      metadata || {},
      this.methodDescriptorGetUserComments
    )
  }

  methodDescriptorSendCommentToPeer = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/SendCommentToPeer',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.PublishCommentToObjRequest,
    dcnet_pb.PublishCommentToObjReply,
    (request: dcnet_pb.PublishCommentToObjRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.PublishCommentToObjReply.deserializeBinary
  )

  sendCommentToPeer(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.PublishCommentToObjReply>

  sendCommentToPeer(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.PublishCommentToObjReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.PublishCommentToObjReply>

  sendCommentToPeer(
    request: dcnet_pb.PublishCommentToObjRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.PublishCommentToObjReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/SendCommentToPeer',
        request,
        metadata || {},
        this.methodDescriptorSendCommentToPeer,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/SendCommentToPeer',
      request,
      metadata || {},
      this.methodDescriptorSendCommentToPeer
    )
  }

  methodDescriptorPushCommentFunOpt = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/PushCommentFunOpt',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.PushCommentFunOptRequest,
    dcnet_pb.PushCommentFunOptReply,
    (request: dcnet_pb.PushCommentFunOptRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.PushCommentFunOptReply.deserializeBinary
  )

  pushCommentFunOpt(
    request: dcnet_pb.PushCommentFunOptRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.PushCommentFunOptReply>

  pushCommentFunOpt(
    request: dcnet_pb.PushCommentFunOptRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.PushCommentFunOptReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.PushCommentFunOptReply>

  pushCommentFunOpt(
    request: dcnet_pb.PushCommentFunOptRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.PushCommentFunOptReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/PushCommentFunOpt',
        request,
        metadata || {},
        this.methodDescriptorPushCommentFunOpt,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/PushCommentFunOpt',
      request,
      metadata || {},
      this.methodDescriptorPushCommentFunOpt
    )
  }

  methodDescriptorPullCommentFunOpts = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/PullCommentFunOpts',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.PullCommentFunOptsRequest,
    dcnet_pb.PullCommentFunOptsReply,
    (request: dcnet_pb.PullCommentFunOptsRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.PullCommentFunOptsReply.deserializeBinary
  )

  pullCommentFunOpts(
    request: dcnet_pb.PullCommentFunOptsRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.PullCommentFunOptsReply>

  pullCommentFunOpts(
    request: dcnet_pb.PullCommentFunOptsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.PullCommentFunOptsReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.PullCommentFunOptsReply>

  pullCommentFunOpts(
    request: dcnet_pb.PullCommentFunOptsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.PullCommentFunOptsReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/PullCommentFunOpts',
        request,
        metadata || {},
        this.methodDescriptorPullCommentFunOpts,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/PullCommentFunOpts',
      request,
      metadata || {},
      this.methodDescriptorPullCommentFunOpts
    )
  }

  methodDescriptorExchangeCommentEdges = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/ExchangeCommentEdges',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.ExchangeCommentEdgesRequest,
    dcnet_pb.ExchangeCommentEdgesReply,
    (request: dcnet_pb.ExchangeCommentEdgesRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.ExchangeCommentEdgesReply.deserializeBinary
  )

  exchangeCommentEdges(
    request: dcnet_pb.ExchangeCommentEdgesRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.ExchangeCommentEdgesReply>

  exchangeCommentEdges(
    request: dcnet_pb.ExchangeCommentEdgesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.ExchangeCommentEdgesReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.ExchangeCommentEdgesReply>

  exchangeCommentEdges(
    request: dcnet_pb.ExchangeCommentEdgesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.ExchangeCommentEdgesReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/ExchangeCommentEdges',
        request,
        metadata || {},
        this.methodDescriptorExchangeCommentEdges,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/ExchangeCommentEdges',
      request,
      metadata || {},
      this.methodDescriptorExchangeCommentEdges
    )
  }

  methodDescriptorDownloadUserComments = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/DownloadUserComments',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.DownloadUserCommentsRequest,
    dcnet_pb.DownloadUserCommentsReply,
    (request: dcnet_pb.DownloadUserCommentsRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.DownloadUserCommentsReply.deserializeBinary
  )

  downloadUserComments(
    request: dcnet_pb.DownloadUserCommentsRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.DownloadUserCommentsReply>

  downloadUserComments(
    request: dcnet_pb.DownloadUserCommentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.DownloadUserCommentsReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.DownloadUserCommentsReply>

  downloadUserComments(
    request: dcnet_pb.DownloadUserCommentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.DownloadUserCommentsReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/DownloadUserComments',
        request,
        metadata || {},
        this.methodDescriptorDownloadUserComments,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/DownloadUserComments',
      request,
      metadata || {},
      this.methodDescriptorDownloadUserComments
    )
  }

  methodDescriptorUserCommentsDownloadReady = new grpcWeb.MethodDescriptor(
    '/dcnet.pb.Service/UserCommentsDownloadReady',
    grpcWeb.MethodType.UNARY,
    dcnet_pb.UserCommentsDownloadReadyRequest,
    dcnet_pb.UserCommentsDownloadReadyReply,
    (request: dcnet_pb.UserCommentsDownloadReadyRequest) => {
      return request.serializeBinary()
    },
    dcnet_pb.UserCommentsDownloadReadyReply.deserializeBinary
  )

  userCommentsDownloadReady(
    request: dcnet_pb.UserCommentsDownloadReadyRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<dcnet_pb.UserCommentsDownloadReadyReply>

  userCommentsDownloadReady(
    request: dcnet_pb.UserCommentsDownloadReadyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError, response: dcnet_pb.UserCommentsDownloadReadyReply) => void
  ): grpcWeb.ClientReadableStream<dcnet_pb.UserCommentsDownloadReadyReply>

  userCommentsDownloadReady(
    request: dcnet_pb.UserCommentsDownloadReadyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError, response: dcnet_pb.UserCommentsDownloadReadyReply) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/dcnet.pb.Service/UserCommentsDownloadReady',
        request,
        metadata || {},
        this.methodDescriptorUserCommentsDownloadReady,
        callback
      )
    }
    return this.client_.unaryCall(
      this.hostname_ + '/dcnet.pb.Service/UserCommentsDownloadReady',
      request,
      metadata || {},
      this.methodDescriptorUserCommentsDownloadReady
    )
  }
}
